name: mi_padre_hurtado
description: "Mi Padre Hurtado - Tarjeta Vecino Digital (port a Flutter)."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_aplicacion.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/comercios/
    - assets/logos/
